"""
Part 3: Send Email Newsletter
This script sends the summarized articles via email
"""

import json
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# Import configuration from config.py
try:
    from config import (
        SENDER_EMAIL,
        SENDER_PASSWORD,
        RECIPIENT_EMAIL,
        SMTP_SERVER,
        SMTP_PORT
    )
except ImportError:
    print("⚠️  ERROR: config.py not found!")
    print("\nPlease make sure config.py has your email settings")
    exit(1)


def create_email_html(articles):
    """
    Create a nicely formatted HTML email from articles
    
    Args:
        articles (list): List of article dictionaries with summaries
        
    Returns:
        str: HTML formatted email content
    """
    
    # Get current date for the newsletter
    today = datetime.now().strftime("%B %d, %Y")
    
    # Start building HTML
    html = f"""
    <html>
    <head>
        <style>
            body {{
                font-family: Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 600px;
                margin: 0 auto;
                padding: 20px;
            }}
            .header {{
                background-color: #2c3e50;
                color: white;
                padding: 20px;
                text-align: center;
                border-radius: 5px;
            }}
            .article {{
                background-color: #f8f9fa;
                padding: 20px;
                margin: 20px 0;
                border-left: 4px solid #3498db;
                border-radius: 5px;
            }}
            .topic {{
                color: #3498db;
                font-size: 12px;
                font-weight: bold;
                text-transform: uppercase;
                margin-bottom: 10px;
            }}
            .title {{
                font-size: 18px;
                font-weight: bold;
                color: #2c3e50;
                margin-bottom: 10px;
            }}
            .summary {{
                font-size: 14px;
                color: #555;
                margin-bottom: 15px;
            }}
            .source {{
                font-size: 12px;
                color: #7f8c8d;
                margin-bottom: 10px;
            }}
            .read-more {{
                display: inline-block;
                padding: 8px 15px;
                background-color: #3498db;
                color: white;
                text-decoration: none;
                border-radius: 3px;
                font-size: 14px;
            }}
            .read-more:hover {{
                background-color: #2980b9;
            }}
            .footer {{
                text-align: center;
                margin-top: 30px;
                padding-top: 20px;
                border-top: 1px solid #ddd;
                color: #7f8c8d;
                font-size: 12px;
            }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>📰 Your Daily News Digest</h1>
            <p>{today}</p>
        </div>
    """
    
    # Add each article
    for i, article in enumerate(articles, 1):
        html += f"""
        <div class="article">
            <div class="topic">{article['topic']}</div>
            <div class="title">{article['title']}</div>
            <div class="source">Source: {article['source']}</div>
            <div class="summary">{article['summary']}</div>
            <a href="{article['url']}" class="read-more">Read Full Article →</a>
        </div>
        """
    
    # Add footer
    html += """
        <div class="footer">
            <p>This newsletter was automatically generated by your AI News Assistant</p>
            <p>Powered by NewsAPI & OpenAI GPT-4o-mini</p>
        </div>
    </body>
    </html>
    """
    
    return html


def send_email(subject, html_content, sender_email, sender_password, recipient_email):
    """
    Send an email using Gmail SMTP
    
    Args:
        subject (str): Email subject line
        html_content (str): HTML content of the email
        sender_email (str): Sender's email address
        sender_password (str): Sender's app password
        recipient_email (str): Recipient's email address
        
    Returns:
        bool: True if successful, False otherwise
    """
    
    try:
        # Create message
        message = MIMEMultipart("alternative")
        message["Subject"] = subject
        message["From"] = sender_email
        message["To"] = recipient_email
        
        # Attach HTML content
        html_part = MIMEText(html_content, "html")
        message.attach(html_part)
        
        # Connect to Gmail SMTP server
        print(f"Connecting to {SMTP_SERVER}:{SMTP_PORT}...")
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()  # Secure the connection
            
            print("Logging in...")
            server.login(sender_email, sender_password)
            
            print(f"Sending email to {recipient_email}...")
            server.send_message(message)
        
        print("✓ Email sent successfully!")
        return True
        
    except smtplib.SMTPAuthenticationError:
        print("❌ ERROR: Authentication failed!")
        print("\nPossible issues:")
        print("1. Wrong email or password")
        print("2. Need to use App Password (not regular Gmail password)")
        print("3. 2-Factor Authentication not enabled")
        print("\nGet App Password: https://myaccount.google.com/apppasswords")
        return False
        
    except smtplib.SMTPException as e:
        print(f"❌ SMTP Error: {e}")
        return False
        
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        return False


def main():
    """
    Main function to load articles and send email
    """
    
    print("=" * 60)
    print("EMAIL NEWSLETTER SENDER - Part 3 Test")
    print("=" * 60)
    print()
    
    # Verify email configuration
    if not SENDER_EMAIL or SENDER_EMAIL == "your_email@gmail.com":
        print("⚠️  ERROR: Please add your sender email to config.py")
        return
    
    if not SENDER_PASSWORD or SENDER_PASSWORD == "your_16_char_app_password":
        print("⚠️  ERROR: Please add your Gmail App Password to config.py")
        print("Get it here: https://myaccount.google.com/apppasswords")
        return
    
    if not RECIPIENT_EMAIL or RECIPIENT_EMAIL == "recipient@gmail.com":
        print("⚠️  ERROR: Please add recipient email to config.py")
        return
    
    # Load summarized articles
    input_file = "summarized_articles.json"
    
    try:
        with open(input_file, "r", encoding="utf-8") as f:
            articles = json.load(f)
    except FileNotFoundError:
        print(f"⚠️  ERROR: '{input_file}' not found!")
        print("Please run 'summarize_articles.py' first.")
        return
    except json.JSONDecodeError:
        print(f"⚠️  ERROR: '{input_file}' is not valid JSON")
        return
    
    if not articles:
        print("⚠️  No articles found in the file.")
        return
    
    print(f"Loaded {len(articles)} articles from '{input_file}'")
    print()
    
    # Create email content
    print("Creating email content...")
    today = datetime.now().strftime("%B %d, %Y")
    subject = f"📰 Your Daily News Digest - {today}"
    html_content = create_email_html(articles)
    print("✓ Email content created")
    print()
    
    # Send email
    success = send_email(
        subject,
        html_content,
        SENDER_EMAIL,
        SENDER_PASSWORD,
        RECIPIENT_EMAIL
    )
    
    if success:
        print()
        print("=" * 60)
        print("SUCCESS! Check your inbox at:")
        print(f"  📧 {RECIPIENT_EMAIL}")
        print("=" * 60)
    else:
        print()
        print("=" * 60)
        print("Email sending failed. Please check the error messages above.")
        print("=" * 60)


if __name__ == "__main__":
    main()